### ISSUE TITLE
Is it possible to extract the edges in the dependency graph via groovy?

### ISSUE THREAD

**Issue by alok15ee** [jenkinsci/depgraph-view-plugin#31]
Hi,
I can't seem to find API's directly available through the Jenkins groovy Sandbox API's.  I can always parse the JSON data but was wondering if there is a straightforward method to find upstream and downstream based on the graph.

Update: I found this https://javadoc.jenkins-ci.org/jenkins/model/Jenkins.html#getDependencyGraph-- but it doesn't support workflow projects.

**Comment by guidograzioli** [comment]
Hello,
the method you found is what the depgraph-plugin uses internally to draw old-style build trigger dependencies (ie. the black arrows). Here is the relevant code: https://github.com/jenkinsci/depgraph-view-plugin/blob/master/src/main/java/hudson/plugins/depgraph_view/model/graph/edge/DependencyGraphEdgeProvider.java

In the groovy console, you can access the graph starting from a project, using this code:

    import hudson.plugins.depgraph_view.model.graph.*;
    import hudson.plugins.depgraph_view.model.graph.edge.*;
    import static hudson.plugins.depgraph_view.model.graph.ProjectNode.node;
    import com.google.common.collect.ImmutableSet;

    def job = Jenkins.instance.items.find { it.name == "maven-pipeline-project2" }
    ImmutableSet providers = ImmutableSet.<EdgeProvider>of(
          new DependencyGraphEdgeProvider(Jenkins.instance),
          new PipelineGraphPublisherEdgeProvider(Jenkins.instance));
    DependencyGraph dg = new GraphCalculator(providers).generateGraph(Collections.singleton(node(job)));
    println dg.getEdges();
    println dg.getGraph().getVertices();

In the provider set you can "pick" edge provider types from here: https://github.com/jenkinsci/depgraph-view-plugin/tree/master/src/main/java/hudson/plugins/depgraph_view/model/graph/edge

**Comment by alok15ee** [comment]
@guidograzioliThanks, this is what exactly I was looking for. Let me give it a try and I will reach out to you again.

**Comment by alok15ee** [comment]
@guidograzioli It always gives me empty nodes and vertices for pipeline jobs.
